name: example
description: "Firebase UI Auth example."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  firebase_ui_auth: ^1.13.1
  firebase_ui_oauth_google: ^1.3.1
  firebase_ui_oauth_apple: ^1.2.19

  sign_in_with_apple: ^6.0.0
  crypto: ^3.0.2
  google_sign_in: ^6.2.1

  cupertino_icons: ^1.0.6

  sizer: ^2.0.15

dependency_overrides:
  firebase_ui_auth:
    git:
      url: https://github.com/orenagiv/FirebaseUI-Flutter.git
      path: packages/firebase_ui_auth
      ref: feature/phone-input-autofocus

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logos/
